// Type definition for the simplified model data
export type ModelBasicInfo = {
  id: string;
  name: string;
  type: "chat" | "image" | "audio" | "video" | "multimodal";
};

// Type definitions for different model pricing structures
type ImageModelPricing = {
  capabilities: ("image-gen" | "image-edit")[];
  perImage: string;
  perThousandRequest: string;
};

type AudioModelPricing = {
  capabilities: ("stt" | "tts" | "audio-gen")[];
  perMinInput: string;
  perSecGenerated: string;
  perTenThousandRequests: string;
};

type VideoModelPricing = {
  capabilities: ("text-video" | "video-edit")[];
  perSecGenerated: string;
  perThousandRequests: string;
};

// Combined type using discriminated union
type ModelPricing = {
  id: string;
  name: string;
} & (
  | { type: "chat" }
  | ({ type: "image" } & ImageModelPricing)
  | ({ type: "audio" } & AudioModelPricing)
  | ({ type: "video" } & VideoModelPricing)
  | { type: "multimodal" }
);

// Array of models with pricing information
export const modelBasicInfo: ModelPricing[] = [
  {
    id: "gpt-4o",
    name: "GPT-4o",
    type: "chat",
  },
  {
    id: "gemini-1-5-pro",
    name: "Gemini 1.5 Pro",
    type: "chat",
  },
  {
    id: "claude-3.5-sonnet",
    name: "Claude 3.5 Sonnet",
    type: "chat",
  },
  {
    id: "sonar-large-32k-online",
    name: "Sonar Large 32k Online",
    type: "chat",
  },
  {
    id: "gpt-4o-mini",
    name: "GPT 4o-mini",
    type: "chat",
  },
  {
    id: "gemini-1.0-pro",
    name: "Gemini 1.0 Pro",
    type: "chat",
  },
  {
    id: "claude-3-opus",
    name: "Claude 3 Opus",
    type: "chat",
  },
  {
    id: "claude-3-sonnet",
    name: "Claude 3 Sonnet",
    type: "chat",
  },
  {
    id: "claude-3-hiaku",
    name: "Claude 3 Hiaku",
    type: "chat",
  },
  {
    id: "sonar-small-32k-online",
    name: "Sonar Small 32k Online",
    type: "chat",
  },
  {
    id: "gpt-4",
    name: "GPT-4",
    type: "chat",
  },
  {
    id: "chatgpt-3-5",
    name: "ChatGPT 3.5",
    type: "chat",
  },
  {
    id: "llama-3-70b-instruct",
    name: "Llama 3 70B Instruct",
    type: "chat",
  },
  {
    id: "mistral-7b-instruct",
    name: "Mistral 7B Instruct",
    type: "chat",
  },
  {
    id: "perplexity",
    name: "Perplexity",
    type: "chat",
  },
  {
    id: "llama-2-13b",
    name: "Llama 2 13B",
    type: "chat",
  },
  {
    id: "dall-e-3",
    name: "DALL-E 3",
    type: "image",
    capabilities: ["image-gen", "image-edit"],
    perImage: "$0.08",
    perThousandRequest: "$80.00",
  },
  {
    id: "stable-diffusion",
    name: "Stable Diffusion",
    type: "image",
    capabilities: ["image-gen"],
    perImage: "$0.05",
    perThousandRequest: "$50.00",
  },
  {
    id: "stable-diffusion-xl",
    name: "Stable Diffusion XL",
    type: "image",
    capabilities: ["image-gen", "image-edit"],
    perImage: "$0.10",
    perThousandRequest: "$100.00",
  },
  {
    id: "titan-image-generator",
    name: "Titan Image Generator",
    type: "image",
    capabilities: ["image-gen"],
    perImage: "$0.12",
    perThousandRequest: "$120.00",
  },
  {
    id: "whisper-ai",
    name: "Whisper AI",
    type: "audio",
    capabilities: ["stt", "tts"],
    perMinInput: "$0.10",
    perSecGenerated: "$0.02",
    perTenThousandRequests: "$150.00",
  },
  {
    id: "musicgen-ai",
    name: "MusicGen AI",
    type: "audio",
    capabilities: ["audio-gen"],
    perMinInput: "$0.15",
    perSecGenerated: "$0.03",
    perTenThousandRequests: "$200.00",
  },
  {
    id: "sora-ai",
    name: "Sora AI",
    type: "video",
    capabilities: ["text-video"],
    perSecGenerated: "$0.50",
    perThousandRequests: "$500.00",
  },
  {
    id: "runway-gen-2",
    name: "Runway Gen-2",
    type: "video",
    capabilities: ["text-video", "video-edit"],
    perSecGenerated: "$0.45",
    perThousandRequests: "$450.00",
  },
  {
    id: "luma-ai-video",
    name: "Luma AI",
    type: "video",
    capabilities: ["text-video"],
    perSecGenerated: "$0.55",
    perThousandRequests: "$550.00",
  },
  {
    id: "kling-ai-video",
    name: "Kling AI",
    type: "video",
    capabilities: ["video-edit"],
    perSecGenerated: "$0.48",
    perThousandRequests: "$480.00",
  },
  {
    id: "animate-diff-video",
    name: "Animate Diff (Video)",
    type: "video",
    capabilities: ["text-video", "video-edit"],
    perSecGenerated: "$0.40",
    perThousandRequests: "$400.00",
  },
];

//  new update coded
export const activeChatAIModels = [
  {
    uid: "gpt-3-5-turbo",
    active: true,
    id: 1,
    dbPricing: true,
    actualModelPricing: true,
    inputTokenPer1M_DB: 0.5,
    outputTokenPer1M_DB: 1.5,
    inputTokenPer1M_Actual: 0.5,
    outputTokenPer1M_Actual: 1.5,
    inputTypes: null,
    per1000Request: "",
  },
  {
    uid: "gpt-4o",
    active: true,
    id: 2,
    dbPricing: true,
    actualModelPricing: true,
    inputTokenPer1M_DB: 2.5,
    outputTokenPer1M_DB: 10,
    inputTokenPer1M_Actual: 2.5,
    outputTokenPer1M_Actual: 10,
    inputTypes: ["text", "image"],
    per1000Request: "",
  },
  {
    uid: "llama-3-70b-instruct",
    active: true,
    id: 5,
    dbPricing: true,
    actualModelPricing: true,
    inputTokenPer1M_DB: 0.72,
    outputTokenPer1M_DB: 0.72,
    inputTokenPer1M_Actual: 0.72,
    outputTokenPer1M_Actual: 0.72,
    inputTypes: ["text"],
    per1000Request: "",
  },
  {
    uid: "yi-large",
    active: true,
    id: 9,
    dbPricing: true,
    actualModelPricing: true,
    inputTokenPer1M_DB: 3,
    outputTokenPer1M_DB: 3,
    inputTokenPer1M_Actual: 3,
    outputTokenPer1M_Actual: 3,
    inputTypes: null,
    per1000Request: "",
  },
  {
    uid: "llama-3-1-405b-instruct",
    active: true,
    id: 11,
    dbPricing: true,
    actualModelPricing: true,
    inputTokenPer1M_DB: 5,
    outputTokenPer1M_DB: 16,
    inputTokenPer1M_Actual: 5,
    outputTokenPer1M_Actual: 16,
    inputTypes: ["text"],
    per1000Request: "",
  },
  {
    uid: "llama-3-1-70b-instruct",
    active: true,
    id: 12,
    dbPricing: true,
    actualModelPricing: true,
    inputTokenPer1M_DB: 0.72,
    outputTokenPer1M_DB: 0.72,
    inputTokenPer1M_Actual: 0.72,
    outputTokenPer1M_Actual: 0.72,
    inputTypes: ["text"],
    per1000Request: "",
  },
  {
    uid: "claude-3-haiku",
    active: true,
    id: 15,
    dbPricing: true,
    actualModelPricing: true,
    inputTokenPer1M_DB: 0.25,
    outputTokenPer1M_DB: 1.25,
    inputTokenPer1M_Actual: 0.25,
    outputTokenPer1M_Actual: 1.25,
    inputTypes: null,
    per1000Request: "",
  },
  {
    uid: "claude-2-1",
    active: true,
    id: 16,
    dbPricing: true,
    actualModelPricing: true,
    inputTokenPer1M_DB: 8,
    outputTokenPer1M_DB: 24,
    inputTokenPer1M_Actual: 8,
    outputTokenPer1M_Actual: 24,
    inputTypes: null,
    per1000Request: "",
  },
  {
    uid: "llama-3-sonar-small-32k-online",
    active: true,
    id: 21,
    dbPricing: true,
    actualModelPricing: true,
    inputTokenPer1M_DB: 0.24,
    outputTokenPer1M_DB: 2,
    inputTokenPer1M_Actual: 0.24,
    outputTokenPer1M_Actual: 2,
    inputTypes: null,
    per1000Request: "",
  },
  {
    uid: "llama-3-sonar-large-32k-online",
    active: true,
    id: 22,
    dbPricing: true,
    actualModelPricing: true,
    inputTokenPer1M_DB: 0.5,
    outputTokenPer1M_DB: 2,
    inputTokenPer1M_Actual: 0.5,
    outputTokenPer1M_Actual: 2,
    inputTypes: null,
    per1000Request: "",
  },
  {
    uid: "mixtral-8x7b-instruct",
    active: true,
    id: 23,
    dbPricing: true,
    actualModelPricing: true,
    inputTokenPer1M_DB: 0.45,
    outputTokenPer1M_DB: 0.75,
    inputTokenPer1M_Actual: 0.45,
    outputTokenPer1M_Actual: 0.75,
    inputTypes: null,
    per1000Request: "",
  },
  {
    uid: "llama-3-1-8b-instruct",
    active: true,
    id: 24,
    dbPricing: true,
    actualModelPricing: true,
    inputTokenPer1M_DB: 0.22,
    outputTokenPer1M_DB: 0.22,
    inputTokenPer1M_Actual: 0.22,
    outputTokenPer1M_Actual: 0.22,
    inputTypes: null,
    per1000Request: "",
  },
  {
    uid: "gpt-4o-mini",
    active: true,
    id: 25,
    dbPricing: true,
    actualModelPricing: true,
    inputTokenPer1M_DB: 0.15,
    outputTokenPer1M_DB: 0.6,
    inputTokenPer1M_Actual: 0.15,
    outputTokenPer1M_Actual: 0.6,
    inputTypes: ["text", "images"],
    per1000Request: "",
  },
  {
    uid: "gpt-4",
    active: true,
    id: 26,
    dbPricing: true,
    actualModelPricing: true,
    inputTokenPer1M_DB: 30,
    outputTokenPer1M_DB: 60,
    inputTokenPer1M_Actual: 30,
    outputTokenPer1M_Actual: 60,
    inputTypes: ["text", "image"],
    per1000Request: "",
  },
  {
    uid: "deepseek-r1",
    active: true,
    id: 30,
    dbPricing: true,
    actualModelPricing: true,
    inputTokenPer1M_DB: 1.35,
    outputTokenPer1M_DB: 5.4,
    inputTokenPer1M_Actual: 1.35,
    outputTokenPer1M_Actual: 5.4,
    inputTypes: ["text"],
    per1000Request: "",
  },
  {
    uid: "o3-mini",
    active: true,
    id: 31,
    dbPricing: true,
    actualModelPricing: true,
    inputTokenPer1M_DB: 1.1,
    outputTokenPer1M_DB: 4.4,
    inputTokenPer1M_Actual: 1.1,
    outputTokenPer1M_Actual: 4.4,
    inputTypes: ["text"],
    per1000Request: "",
  },
  {
    uid: "o1",
    active: true,
    id: 33,
    dbPricing: true,
    actualModelPricing: true,
    inputTokenPer1M_DB: 15,
    outputTokenPer1M_DB: 60,
    inputTokenPer1M_Actual: 15,
    outputTokenPer1M_Actual: 60,
    inputTypes: ["text"],
    per1000Request: "",
  },
  {
    uid: "ministral-3b",
    active: true,
    id: 34,
    dbPricing: true,
    actualModelPricing: true,
    inputTokenPer1M_DB: 0.04,
    outputTokenPer1M_DB: 0.04,
    inputTokenPer1M_Actual: 0.04,
    outputTokenPer1M_Actual: 0.04,
    inputTypes: ["text"],
    per1000Request: "",
  },
  {
    uid: "phi-4",
    active: true,
    id: 35,
    dbPricing: true,
    actualModelPricing: true,
    inputTokenPer1M_DB: 0.125,
    outputTokenPer1M_DB: 0.5,
    inputTokenPer1M_Actual: 0.125,
    outputTokenPer1M_Actual: 0.5,
    inputTypes: ["text"],
    per1000Request: "",
  },
  {
    uid: "gpt-4-5",
    active: true,
    id: 36,
    dbPricing: true,
    actualModelPricing: true,
    inputTokenPer1M_DB: 75,
    outputTokenPer1M_DB: 150,
    inputTokenPer1M_Actual: 75,
    outputTokenPer1M_Actual: 150,
    inputTypes: ["text", "image"],
    per1000Request: "",
  },
  {
    uid: "deepseek-v3",
    active: true,
    id: 37,
    dbPricing: true,
    actualModelPricing: true,
    inputTokenPer1M_DB: 0.27,
    outputTokenPer1M_DB: 1.1,
    inputTokenPer1M_Actual: 0.27,
    outputTokenPer1M_Actual: 1.1,
    inputTypes: ["text"],
    per1000Request: "",
  },
  {
    uid: "mistral-small-3-1",
    active: true,
    id: 38,
    dbPricing: true,
    actualModelPricing: true,
    inputTokenPer1M_DB: 1,
    outputTokenPer1M_DB: 3,
    inputTokenPer1M_Actual: 1,
    outputTokenPer1M_Actual: 3,
    inputTypes: ["text"],
    per1000Request: "",
  },
  {
    uid: "jamba-1-5-large",
    active: true,
    id: 39,
    dbPricing: true,
    actualModelPricing: true,
    inputTokenPer1M_DB: 2,
    outputTokenPer1M_DB: 8,
    inputTokenPer1M_Actual: 2,
    outputTokenPer1M_Actual: 8,
    inputTypes: ["text"],
    per1000Request: "",
  },
  {
    uid: "jamba-1-5-mini",
    active: true,
    id: 40,
    dbPricing: true,
    actualModelPricing: true,
    inputTokenPer1M_DB: 0.2,
    outputTokenPer1M_DB: 0.4,
    inputTokenPer1M_Actual: 0.2,
    outputTokenPer1M_Actual: 0.4,
    inputTypes: ["text"],
    per1000Request: "",
  },
  {
    uid: "gemini-2-0-flash",
    active: true,
    id: 41,
    dbPricing: true,
    actualModelPricing: true,
    inputTokenPer1M_DB: 0.15,
    outputTokenPer1M_DB: 0.6,
    inputTokenPer1M_Actual: 0.15,
    outputTokenPer1M_Actual: 0.6,
    inputTypes: null,
    per1000Request: "",
  },
  {
    uid: "grok-2",
    active: true,
    id: 42,
    dbPricing: true,
    actualModelPricing: true,
    inputTokenPer1M_DB: 2,
    outputTokenPer1M_DB: 10,
    inputTokenPer1M_Actual: 2,
    outputTokenPer1M_Actual: 10,
    inputTypes: ["text"],
    per1000Request: "",
  },
  {
    uid: "grok-2-vision",
    active: true,
    id: 43,
    dbPricing: true,
    actualModelPricing: true,
    inputTokenPer1M_DB: 2,
    outputTokenPer1M_DB: 10,
    inputTokenPer1M_Actual: 2,
    outputTokenPer1M_Actual: 10,
    inputTypes: ["text", "image"],
    per1000Request: "",
  },
  {
    uid: "o4-mini",
    active: true,
    id: 53,
    dbPricing: true,
    actualModelPricing: true,
    inputTokenPer1M_DB: 1.1,
    outputTokenPer1M_DB: 4.4,
    inputTokenPer1M_Actual: 1.1,
    outputTokenPer1M_Actual: 4.4,
    inputTypes: ["text", "image"],
    per1000Request: "",
  },
  {
    uid: "gpt-4-1-nano",
    active: true,
    id: 54,
    dbPricing: true,
    actualModelPricing: true,
    inputTokenPer1M_DB: 0.1,
    outputTokenPer1M_DB: 0.4,
    inputTokenPer1M_Actual: 0.1,
    outputTokenPer1M_Actual: 0.4,
    inputTypes: ["text"],
    per1000Request: "",
  },
  {
    uid: "o3",
    active: true,
    id: 55,
    dbPricing: true,
    actualModelPricing: true,
    inputTokenPer1M_DB: 10,
    outputTokenPer1M_DB: 40,
    inputTokenPer1M_Actual: 10,
    outputTokenPer1M_Actual: 40,
    inputTypes: ["text"],
    per1000Request: "",
  },
  {
    uid: "gpt-4-1",
    active: true,
    id: 56,
    dbPricing: true,
    actualModelPricing: true,
    inputTokenPer1M_DB: 2,
    outputTokenPer1M_DB: 8,
    inputTokenPer1M_Actual: 2,
    outputTokenPer1M_Actual: 8,
    inputTypes: ["text"],
    per1000Request: "",
  },
  {
    uid: "llama-4-maverick-17b",
    active: true,
    id: 57,
    dbPricing: true,
    actualModelPricing: true,
    inputTokenPer1M_DB: 0.24,
    outputTokenPer1M_DB: 0.97,
    inputTokenPer1M_Actual: 0.24,
    outputTokenPer1M_Actual: 0.97,
    inputTypes: null,
    per1000Request: "",
  },
  {
    uid: "nova-pro",
    active: true,
    id: 58,
    dbPricing: true,
    actualModelPricing: true,
    inputTokenPer1M_DB: 0.8,
    outputTokenPer1M_DB: 3.2,
    inputTokenPer1M_Actual: 0.8,
    outputTokenPer1M_Actual: 3.2,
    inputTypes: null,
    per1000Request: "",
  },
  {
    uid: "gemini-2-5-pro",
    active: true,
    id: 62,
    dbPricing: true,
    actualModelPricing: true,
    inputTokenPer1M_DB: 1.25,
    outputTokenPer1M_DB: 10,
    inputTokenPer1M_Actual: null,
    outputTokenPer1M_Actual: null,
    inputTypes: ["text", "image", "audio", "video"],
    per1000Request: "",
  },
  {
    uid: "gemini-2-5-flash",
    active: true,
    id: 63,
    dbPricing: true,
    actualModelPricing: true,
    inputTokenPer1M_DB: 0.15,
    outputTokenPer1M_DB: 0.6,
    inputTokenPer1M_Actual: null,
    outputTokenPer1M_Actual: null,
    inputTypes: ["text", "image", "audio"],
    per1000Request: "",
  },
  {
    uid: "gemini-2-0-flash-lite",
    active: true,
    id: 64,
    dbPricing: true,
    actualModelPricing: true,
    inputTokenPer1M_DB: 0.075,
    outputTokenPer1M_DB: 0.3,
    inputTokenPer1M_Actual: null,
    outputTokenPer1M_Actual: null,
    inputTypes: null,
    per1000Request: "",
  },
];

// image models
export const actualIMagePricing = [
  {
    Uids: "DALL-E 3",
    Id: 19,
    "DB Pricing Per 1000 Images": 40,
    "Actual Model Pricing": "",
  },
  {
    Uids: "Stable Diffusion XL",
    Id: 20,
    "DB Pricing Per 1000 Images": 65,
    "Actual Model Pricing": "",
  },
  {
    Uids: "Titan Image Generator",
    Id: 27,
    "DB Pricing Per 1000 Images": 10,
    "Actual Model Pricing": "",
  },
  {
    Uids: "Grok 2 Image",
    Id: 44,
    "DB Pricing Per 1000 Images": 70,
    "Actual Model Pricing": "",
  },
  {
    Uids: "Stable Image Ultra",
    Id: 45,
    "DB Pricing Per 1000 Images": 80,
    "Actual Model Pricing": "",
  },
  {
    Uids: "Stable Image Core",
    Id: 46,
    "DB Pricing Per 1000 Images": 30,
    "Actual Model Pricing": "",
  },
  {
    Uids: "Nova Canvas",
    Id: 47,
    "DB Pricing Per 1000 Images": 80,
    "Actual Model Pricing": "",
  },
  {
    Uids: "Bria 2.3 Fast",
    Id: 52,
    "DB Pricing Per 1000 Images": 40,
    "Actual Model Pricing": "",
  },
  {
    Uids: "Imagen 3",
    Id: 67,
    "DB Pricing Per 1000 Images": 40,
    "Actual Model Pricing": "",
  },
  {
    Uids: "Imagen 3 Fast",
    Id: 68,
    "DB Pricing Per 1000 Images": 20,
    "Actual Model Pricing": "",
  },
  {
    Uids: "Imagen 2",
    Id: 69,
    "DB Pricing Per 1000 Images": 20,
    "Actual Model Pricing": "",
  },
  {
    Uids: "Imagen 4",
    Id: 76,
    "DB Pricing Per 1000 Images": 40,
    "Actual Model Pricing": "",
  },
  {
    Uids: "Imagen 4 Ultra",
    Id: 77,
    "DB Pricing Per 1000 Images": 40,
    "Actual Model Pricing": "",
  },
  {
    Uids: "Gemini 2.0 Flash Image Generation",
    "DB Pricing Per 1000 Images": "70",
  },
];

// audio models
export type AudioModelType = {
  Uids: string;
  Input?: number | string;
  Output?: number | string;
  "Estimated cost"?: string;
  "Estimated cost per minute"?: string;
  "Estimated cost per minute of video"?: string;
  price?: string;
};

export const activeAudioModels: AudioModelType[] = [
  {
    Uids: "gpt-4o-mini-tts",
    Input: 0.6,
    Output: "-",
    "Estimated cost": "0.015 minute",
  },
  {
    Uids: "gpt-4o-transcribe",
    Input: 2.5,
    Output: 10.0,
    "Estimated cost": "0.0006 minute",
  },
  {
    Uids: "gpt-4o-mini-transcribe",
    Input: 1.25,
    Output: 5.0,
    "Estimated cost": "0.0003 minute",
  },
  {
    Uids: "elevenlabs-multilingual-v2",
    Input: "-",
    Output: 2.0,
    "Estimated cost": "0.015 minute",
  },
  {
    Uids: "scribe-v1",
    Input: 3.0,
    Output: "-",
    "Estimated cost": "0.0003 minute",
  },
  {
    Uids: "lyria",
    "Estimated cost per minute of video": "$0.06 per 30 seconds",
  },
];

// video

export const activeVideoModels = [
  {
    Uids: "nova-real",
    "price per second of video": "$0.08 ",
  },
  {
    Uids: "ray-2",
    "price per second of video 720,24fps": "$1.50",
    "price per second of video 540,24fps": "$0.75",
  },
  {
    Uids: "veo-2",
    "price per second of video": "$0.50",
  },
];
